[package]
name = "keyboard-display-utility"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.33.2", features = ["default"] }
inputbot = "0.6.0"
serde = { version = "1.0.228", features = ["derive"] }
strum = "0.25"
strum_macros = "0.25"
toml = "0.9.8"
