[package]
name = "keyboard-display-utility"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.33.2", features = ["default"] }
inputbot = "0.6.0"
strum = "0.25"
strum_macros = "0.25"
